osx_image: xcode7.2
language: objective-c
cache: cocoapods

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- gem install cocoapods

script:
- xctool clean build -project Hue.xcodeproj -scheme Hue -sdk iphonesimulator
- xctool test -project Hue.xcodeproj -scheme Hue -sdk iphonesimulator -destination name="iPhone 6"
