osx_image: xcode7.2
language: objective-c
cache: cocoapods

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- gem install cocoapods
- pod install --project-directory=Pod

script:
- xctool clean build -workspace Pod/Pod.xcworkspace -scheme Tests -sdk iphonesimulator
- xctool test -workspace Pod/Pod.xcworkspace -scheme Tests -sdk iphonesimulator